<a href="https://colab.research.google.com/github/GabrielaRC29/DV_23_II/blob/main/0_3__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.what is a data structure?**

Something that let me store several values.



# **2. Linear Algebra - Numpy**


Numpy = Numerical Python

In [1]:
#Libraries
import numpy as np

## 2.1 Numpy arrays - Vectors and Matrices

In [2]:
# Column Vector
x = np.array([[1],[2],[3]])
print(x)
print(x.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [3]:
# Row Vector
y = np.array([[3, 4, 5]])
print(y)
print(y.shape)

[[3 4 5]]
(1, 3)


In [7]:
#Matrix
m = np.array([[1,2,3],
             [ 4,5,6],
              [7,8,9]])
print(m)
print(m.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [5]:
# A nice trick
n,m = m.shape
print('number of rows in n:', n)
print('number of Colum in m:', m)

number of rows in n: 3
number of Colum in m: 3


## 2.2. Slicing matrices

In [8]:
# Access information
## For vector
### Column Vector
print(x[2])
### Row vector
print(y[0,0])

## For matrix
print(m[1,1])



[3]
3
5


In [ ]:
# Exercise- Practice
## Using a for loop display/print the number of the row
## the number of the column, and the element for
## every element in the matrix M
for j in range(0,3):
  for i in range(0,3):
    print("Row Position", j+1, "Column Position", i+1, "Element:",m[j,i])



Row Position 1 Column Position 1 Element: 1
Row Position 1 Column Position 2 Element: 2
Row Position 1 Column Position 3 Element: 3
Row Position 2 Column Position 1 Element: 4
Row Position 2 Column Position 2 Element: 5
Row Position 2 Column Position 3 Element: 6
Row Position 3 Column Position 1 Element: 7
Row Position 3 Column Position 2 Element: 8
Row Position 3 Column Position 3 Element: 9


##2.2. Extract subsets

In [ ]:
# Extract an entire row
print(m[1,])

# Extract an entire column
print(m[:,1])

[4 5 6]
[2 5 8]


In [ ]:
# Extract the elements of the
# Last row and columns 2 and 3
print(m[2,1:3])

[8 9]


In [ ]:
# Extract the elements of the
# Frist two rows and last two columns

print(m[0:2,1:3])

[[2 3]
 [5 6]]


## 2.4. Useful methos

In [ ]:
# Zeros
## One dimension
z1 = np.zeros(7)
print("z1")
print(z1)
## Two dimensions
z2 = np.zeros((3,5))
print("z2")
print(z2)

z1
[0. 0. 0. 0. 0. 0. 0.]
z2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# ones

## One dimension
o1 = np.ones(7)
print("o1")
print(o1)
## Two dimensions
o2 = np.ones((3,5))
print("o2")
print(o2)

o1
[1. 1. 1. 1. 1. 1. 1.]
o2
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Full
## One dimension
f1 = np.full(3,13)
print("f1")
print(f1)

## Two dimension
f2 = np.full((3,2),17)
print("f2")
print(f2)

f1
[13 13 13]
f2
[[17 17]
 [17 17]
 [17 17]]


In [ ]:
# Sequence

##Simple
s1 = np. arange(10)
print("s1")
print(s1)

## Not that simple
s2 = np. arange(start =2, stop = 15)
print("s2")
print(s2)

## Custom
s3 = np. arange(start =2, stop = 15, step = 3)
print("s3")
print(s3)

s1
[0 1 2 3 4 5 6 7 8 9]
s2
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
s3
[ 2  5  8 11 14]


In [ ]:
#Linear space
l1 = np.linspace(0,2,5)
print("l1")
print(l1)

l1
[0.  0.5 1.  1.5 2. ]


## 2.5 Random numbers

In [ ]:
# Uniform distribution - [0, 1)
# np.random.seed(1234)  # Fix the similation
np.random.rand()


0.6221087710398319

In [ ]:
# Example - Toss coin simulation
if np.random.rand() <= 0.5:
  print("Heads")
else:
  print("Tails")

Heads


if/ else with more than 2 options

In [13]:
# Example - three options

toss = np.random.rand()

if toss <= 0.4:
  print('green')
elif toss > 0.4 and toss <= 0.6:
  print('blue')
else:
  print('red')

green


In [ ]:
## Exercise
## Simulate three coin tosses and
## present the results according these rules:

## 1. Three heads, result: 'You win COP 100K'
## 2. Three tails, result: 'You win COP 90K'
## 3. Otherwise, result: 'You loose'


In [28]:
# Example - Toss coin simulation

# coin <= 0.5 is heads and else is tails

coin1 = np.random.rand()
coin2 = np.random.rand()
coin3 = np.random.rand()


if coin1 <= 0.5 and coin2 <= 0.5 and coin3 <= 0.5:
  print('Three heads:','You win COP 100K')
elif coin1 > 0.5 and coin2 > 0.5 and coin3 > 0.5:
  print('Three tails:', 'You win 90k')
else:
  print('You loose')

Three heads: You win COP 100K


In [29]:
np.random.rand(3)


array([0.74350561, 0.50256088, 0.50304967])

In [39]:
tosses = np.random.rand(3)

if np.all(tosses <= 0.5):
  print('Three heads:','You win COP 100K')
elif np.all(tosses > 0.5):
  print('Three tails:', 'You win 90k')
else:
  print('You loose')

You loose


In [41]:
# Example - Triangular Distribution
np.random.triangular(100,200,500,7)

array([154.16371899, 316.48888508, 201.89790417, 227.45455467,
       276.05718961, 227.54718766, 310.47874613])

In [92]:
tosses = np.random.rand(7)

if np.all(tosses <= 0.03):
  print('Negativo','100')
elif np.all(tosses > 0.7):
  print('Promedio', '200')
else:
  print('Excelente','500')

Excelente 500


In [115]:
## Sales
bs = 100
av = 200
gs = 500

## Probabilities
pb = 1/30
pg = 8/30

n= 7 # number of days or iterate

for i in range ( 1, n+1):
 day = np.random.rand()
 if day <= pb:
  print(bs)
 elif day > 1 - pg:
  print(gs)
 else:
  print(av)


200
200
200
200
500
200
200
